### PR TITLE
fix: change edit and new event to always include tzid

### LINKED ISSUE #274: Moving event results in wrong time being displayed in email
When changing the date of an event, the notifier displays the wrong time (timezone offset) in the generated output

### PR DESCRIPTION
**Pull request by niri81**
This causes any new and edited event to always have TZIDs in the generated iCal file, which fixes #274.

Edited events keep the previous TZID (i.e. previous start date TZID -> new start date TZID, analogous for end date), whilst new events use the TZID of the user's browser (with time.Locale as fallback) and also include it in the generated iCal as VTimezone.

### CODE REVIEW

File: cmd/ical-relay/api.go [hunk 1]
```diff
@@ -391,20 +391,38 @@ func newentryjsonApiHandler(w http.ResponseWriter, r *http.Request) {
...
+
 		if eventjson["summary"] != "" {
 			event.SetSummary(eventjson["summary"])
 		}
 		if eventjson["location"] != "" {
 			event.SetLocation(eventjson["location"])
 		}
+		var tz *time.Location
+		if tz_str, ok := eventjson["timezone"]; !ok {
+			requestLogger.Warnln("No timezone given in new event payload. Will use locale as fallback")
```
Comment (Sarsum) [inline cmd/ical-relay/api.go]:
```suggestion
			requestLogger.Warnln("No timezone given in new event payload. Will use local as fallback")
```

File: cmd/ical-relay/templates/edit.html [hunk 2]
```diff
@@ -107,11 +107,11 @@ <h1 class="mb-3">
         }
         let start = dayjs(document.getElementById("start").value);
         if (!start.isSame(originalStart)) {
-            event.start = start.toISOString();
+            event.start = start.format("YYYY-MM-DDTHH:mm:ssZ");
```
Comment (Sarsum) [inline cmd/ical-relay/templates/edit.html:110]: golang does not support timezone offsets when "Z" is at the end of the time string, as it indicated the time being UTC (https://en.wikipedia.org/wiki/ISO_8601)

Applies also to line 114 and newevent.html 93 and 95

**Review by Sarsum — CHANGES_REQUESTED** [review]

File: cmd/ical-relay/templates/edit.html (hunk 2 above)
Comment (niri81) [reply cmd/ical-relay/templates/edit.html:110]: This is the dayJS format function, where Z will return the UTC offset (see: https://day.js.org/docs/en/display/format)

Comment (Sarsum) [reply cmd/ical-relay/templates/edit.html:110]: ***** ***** I hate different formats

File: cmd/ical-relay/api.go (hunk 1 above)
Comment (niri81) [reply cmd/ical-relay/api.go]: Thanks :D

**Comment by Sarsum** [comment]
looks good so far, thank you very much!
I need to test it once I have time for it

**Comment by niri81** [comment]
Sure, no problem. Take your time for testing 😄

**Review by Sarsum — APPROVED** [review]

**Review by Sarsum — CHANGES_REQUESTED** [review]
we need to change the commit of the submodule to one from the original repo, once its merged there

**Review by Sarsum — APPROVED** [review]
lgtm
